from datetime import timedelta

ACCESS_TOKEN_LIFETIME_TO_MINUTE = 10
REFRESH_TOKEN_TOKEN_LIFETIME_TO_DAYS = 31


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=ACCESS_TOKEN_LIFETIME_TO_MINUTE),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=REFRESH_TOKEN_TOKEN_LIFETIME_TO_DAYS),
}
